import { Sawarabi_Gothic } from 'next/font/google';
import localFont from "next/font/local";
import type { Metadata } from "next";

import { CheckIsMobile } from '@/shared/tools/checkIsMobile';
import { Footer, FormPopUp, Header } from "@/shared/components";

const sawarabi = Sawarabi_Gothic({
  weight: "400",
  variable: '--font-sawarabi',
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap',
})

const kyivTypeTitling = localFont({
  src: [
    {
      path: "./fonts/KyivTypeTitling/KyivTypeTitling-Regular.woff",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/KyivTypeTitling/KyivTypeTitling-Bold.woff",
      weight: "600",
      style: "normal"
    }
  ],
  variable: "--font-kyiv-type-titling"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.scss";
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="uk">
      <body
        className={`${kyivTypeTitling.variable} ${sawarabi.variable} antialiased`}
      >
        <Header />
        <main className='relative z-[0]'>
          {children}
          <FormPopUp />
          <CheckIsMobile />
        </main>
        <Footer />
      </body>
    </html>
  );
}
